### ISSUE TITLE
Queue name as routing key

### ISSUE THREAD

**Issue by kraih** [inway/mojo-rabbitmq-client#12]
This looks like a bug, the queue name is hardcoded as routing key [here](https://github.com/inway/mojo-rabbitmq-client/blob/4ac402a2f881e0da2b2e1da73ab5e321d97b60bb/lib/Mojo/RabbitMQ/Client/Consumer.pm#L50) in Mojo::RabbitMQ::Client::Consumer.

**Comment by tyldum** [comment]
See #5

**Comment by SPodjasek** [comment]
@kraih Your're right, I believe that all of this:
https://github.com/inway/mojo-rabbitmq-client/blob/4ac402a2f881e0da2b2e1da73ab5e321d97b60bb/lib/Mojo/RabbitMQ/Client/Consumer.pm#L47-L53
should be optional, clearly requested by developer.

IMHO Queue binding is part of RabbitMQ setup, not to be enforced by consumer. 
It was made that way as most common case, to speed up some things up for me (100% of my queues have `routing_key` as `queue_name`).
