### ISSUE TITLE
Publisher does not appear to work at all

### ISSUE THREAD

**Issue by kraih** [inway/mojo-rabbitmq-client#14]
I've tried the minimal example from the documentation.
```perl
use Mojo::Base -strict;

use Mojo::RabbitMQ::Client;
my $publisher
  = Mojo::RabbitMQ::Client->publisher(url => 'amqp://.../?exchange=pubsub&queue=test');
$publisher->on(success => sub { say "Publisher ready" });
$publisher->on(error => sub { say 'Error: ', pop });
$publisher->publish('plain text');
$publisher->publish({encode => {to => 'json'}});

Mojo::IOLoop->start unless Mojo::IOLoop->is_running;
```
And all i got was this.
```
Mojo::Reactor::Poll: I/O watcher failed: Can't call method "_read" on an undefined value at /usr/lib/perl5/vendor_perl/5.26.1/Mojo/RabbitMQ/Client.pm line 344.
Mojo::Reactor::Poll: Timer failed: Can't use an undefined value as a HASH reference at /usr/lib/perl5/vendor_perl/5.26.1/Mojo/RabbitMQ/Client/Publisher.pm line 40.
```

**Comment by kraih** [comment]
In my experience that error hints at a memory management problem. Some `$self` being weakend when it shouldn't and getting cleaned up too early. A fairly serious problem.

**Comment by SPodjasek** [comment]
Apparently publisher API needs some redesign. Second call to `->publish` issues second connection attempt which messes all things up.

**Comment by SPodjasek** [comment]
@kraih Please check latest Publisher API as in 5a7cf91 which uses Mojo::Promise:

```perl
use Mojo::RabbitMQ::Client;
my $publisher = Mojo::RabbitMQ::Client->publisher(
  url => 'amqp://guest:guest@127.0.0.1:5672/?exchange=mojo&routing_key=mojo'
);

# In void context this method call is blocking (just uses Promise->wait behind the scene)
$publisher->publish('plain text');

# But in any other context it returns a promise
$publisher->publish(
  {encode => { to => 'json'}},
  routing_key => 'mojo_mq'
)->then(sub {
  say "Message published";
})->catch(sub {
  die "Publishing failed"
})->wait;
```

**Comment by christopherraa** [comment]
@SPodjasek When reading both `Mojo::RabbitMQ::Client::Consumer->start()` (70+ lines) and `Mojo::RabbitMQ::Client::Publisher->publish()` (100+ lines) it strikes me that both of those methods try to do a lot of things. Is this on purpose or just how things have evolved?

In my opinion the sheer length and amount of things both modules have in the mentioned method makes it less maintainable and makes both modules a lot less flexible than they could be. Is this something to address?

**Comment by jonisno** [comment]
Is this suposed to be closed? The publisher currently functions fine.

**Comment by kraih** [comment]
Yes, the publisher seems to work fine now.
