### ISSUE TITLE
The encode_json function is never imported

### ISSUE THREAD

**Issue by kraih** [inway/mojo-rabbitmq-client#15]
This is kind of related to #14, the module `Mojo::RabbitMQ::Client::Publisher` uses but never imports the function `encode_json` [here](https://metacpan.org/source/SEBAPOD/Mojo-RabbitMQ-Client-0.0.9/lib/Mojo/RabbitMQ/Client/Publisher.pm#L44).

**Comment by SPodjasek** [comment]
Thnx, fixed
