### ISSUE TITLE
repo and tarballs include non-free file without notification

### ISSUE THREAD

**Issue by AdamWill** [inway/mojo-rabbitmq-client#37]
The top-level `LICENSE` file is the Artistic License, and the top-level `README.md` file just says "This program is free software, you can redistribute it and/or modify it under the terms of the Artistic License version 2.0."

However, both the repo and the tarball distributions include two files that are not under the Artistic License - the AMQP specs in `share/`. The 0.8 spec is not freely licensed at all, which is a problem for distributions with strict licensing policies: in Fedora we actually have to ship a modified tarball with this file stripped out. The 0.9.1 extended spec is freely licensed, but not under the Artistic license - it is under a BSD-style license.

It'd be ideal for Fedora if the 0.8 spec was dropped and replaced with simply a reference to a URL in the `README` or something, as then we wouldn't have to modify the tarball every time. For the 0.9.1 extended spec, it'd be useful to add a line to the `README` explaining it is not under Artistic.

**Comment by SPodjasek** [comment]
Thanks for pointing this out, fixed and released in 0.3.0
