### ISSUE TITLE
Undeclared dependency on List::MoreUtils

### ISSUE THREAD

**Issue by andk** [inway/mojo-rabbitmq-client#4]
As per subject. Grep:

http://search.cpan.org/grep?release=Mojo-RabbitMQ-Client-0.0.6;string=List::MoreUtils;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/75421452

HTH&&Thanks,

**Comment by SPodjasek** [comment]
Thanks. Missed that it is in debian `perl-base` but not in perl *Core modules*.

**Comment by Grinnz** [comment]
FYI, List::Util is core and provides the same 'none' function since version 1.33 (you should still declare this dependency, because older versions of power don't have version 1.33 and will need to install it)
